name: PHP Lint & Codeception
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        experimental: [false]
    
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: PHP Lint
      continue-on-error: true
      run: if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
    
    - name: Install NPM Dependency
      run: npm install -g grunt-cli && npm install
    
    - name: Grunt lint
      run: grunt lint --force
    
    - name: Grunt minify
      run: grunt minify
